version: '3'

services:
    db:
        image: postgres
        ports:
            - "5432:5432"
    redis:
        image: redis
        ports:
          - "6379:6379"
    api:
        build: .
        image: django
        command: python manage.py runserver 0.0.0.0:8000
        volumes:
          - .:/code
        ports:
          - "8000:8000"
        depends_on:
          - db
          - redis
    migration:
        image: django
        command: python manage.py migrate --noinput
        volumes:
          - .:/code
        depends_on:
          - db
    web:
        build: ./web
        ports:
            - "80:80"
        depends_on:
            - api
